openapi: 3.0.3
info:
  title: User Management API
  description: API for managing users with intentional security issues for demonstration
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key authentication

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique user identifier
        email:
          type: string
          format: email
          description: User email address
        password:
          type: string
          description: User password (SENSITIVE!)
        apiKey:
          type: string
          description: User's personal API key (SENSITIVE!)
        name:
          type: string
          description: User's display name
      required:
        - id
        - email
        - name

    Credentials:
      type: object
      properties:
        username:
          type: string
          description: Login username
        password:
          type: string
          description: Login password (SENSITIVE!)
        secret:
          type: string
          description: Two-factor secret (SENSITIVE!)
        token:
          type: string
          description: Session token (SENSITIVE!)
      required:
        - username
        - password

    UserList:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        total:
          type: integer

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      tags:
        - users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - users
      # INTENTIONAL: No security requirement!
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a user by ID
      operationId: getUser
      tags:
        - users
      security:
        - bearerAuth: []
        - apiKey: []
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a user
      operationId: updateUser
      tags:
        - users
      # INTENTIONAL: No security requirement!
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete a user
      operationId: deleteUser
      tags:
        - users
      # INTENTIONAL: No security requirement!
      responses:
        '204':
          description: User deleted

  /internal/debug:
    get:
      summary: Debug endpoint
      operationId: getDebugInfo
      tags:
        - internal
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Debug information
          content:
            application/json:
              schema:
                type: object

  /_system/health:
    get:
      summary: System health check
      operationId: healthCheck
      tags:
        - system
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

tags:
  - name: users
    description: User management operations
  - name: internal
    description: Internal debugging endpoints
  - name: system
    description: System management endpoints
