package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/erraggy/oastools/parser"
)

// oas2CodeGenerator handles code generation for OAS 2.0 documents
type oas2CodeGenerator struct {
	g      *Generator
	doc    *parser.OAS2Document
	result *GenerateResult
	// schemaNames maps schema references to generated type names
	schemaNames map[string]string
}

func newOAS2CodeGenerator(g *Generator, doc *parser.OAS2Document, result *GenerateResult) *oas2CodeGenerator {
	return &oas2CodeGenerator{
		g:           g,
		doc:         doc,
		result:      result,
		schemaNames: make(map[string]string),
	}
}

// generateTypes generates type definitions from schemas
func (cg *oas2CodeGenerator) generateTypes() error {
	var buf bytes.Buffer

	// Write header
	buf.WriteString("// Code generated by oastools. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", cg.result.PackageName))

	// Collect imports
	imports := make(map[string]bool)

	// Process schemas from definitions
	var schemas []oas2SchemaEntry
	if cg.doc.Definitions != nil {
		for name, schema := range cg.doc.Definitions {
			if schema == nil {
				continue
			}
			schemas = append(schemas, oas2SchemaEntry{name: name, schema: schema})
			cg.schemaNames["#/definitions/"+name] = toTypeName(name)
		}
	}

	// Sort schemas for deterministic output
	sort.Slice(schemas, func(i, j int) bool {
		return schemas[i].name < schemas[j].name
	})

	// Check for time imports
	for _, entry := range schemas {
		if needsTimeImport(entry.schema) {
			imports["time"] = true
			break
		}
	}

	// Write imports
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		var importList []string
		for imp := range imports {
			importList = append(importList, imp)
		}
		sort.Strings(importList)
		for _, imp := range importList {
			buf.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		buf.WriteString(")\n\n")
	}

	// Generate each schema
	for _, entry := range schemas {
		code, err := cg.generateSchemaType(entry.name, entry.schema)
		if err != nil {
			cg.addIssue("definitions."+entry.name, fmt.Sprintf("failed to generate type: %v", err), SeverityWarning)
			continue
		}
		buf.WriteString(code)
		buf.WriteString("\n")
		cg.result.GeneratedTypes++
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		cg.addIssue("types.go", fmt.Sprintf("failed to format generated code: %v", err), SeverityWarning)
		formatted = buf.Bytes()
	}

	cg.result.Files = append(cg.result.Files, GeneratedFile{
		Name:    "types.go",
		Content: formatted,
	})

	return nil
}

// oas2SchemaEntry holds a schema name and its definition
type oas2SchemaEntry struct {
	name   string
	schema *parser.Schema
}

// generateSchemaType generates Go code for a schema type
func (cg *oas2CodeGenerator) generateSchemaType(name string, schema *parser.Schema) (string, error) {
	var buf bytes.Buffer

	typeName := toTypeName(name)

	// Handle $ref
	if schema.Ref != "" {
		refType := cg.resolveRef(schema.Ref)
		buf.WriteString(fmt.Sprintf("// %s is an alias for %s.\n", typeName, refType))
		buf.WriteString(fmt.Sprintf("type %s = %s\n", typeName, refType))
		return buf.String(), nil
	}

	// Write documentation
	if schema.Description != "" {
		buf.WriteString(fmt.Sprintf("// %s %s\n", typeName, cleanDescription(schema.Description)))
	} else {
		buf.WriteString(fmt.Sprintf("// %s represents the %s schema.\n", typeName, name))
	}

	// Determine schema type
	schemaType := getSchemaType(schema)

	switch schemaType {
	case "object":
		// Generate struct
		buf.WriteString(fmt.Sprintf("type %s struct {\n", typeName))
		if schema.Properties != nil {
			// Sort properties for deterministic output
			var propNames []string
			for propName := range schema.Properties {
				propNames = append(propNames, propName)
			}
			sort.Strings(propNames)

			for _, propName := range propNames {
				propSchema := schema.Properties[propName]
				if propSchema == nil {
					continue
				}

				goType := cg.schemaToGoType(propSchema, isRequired(schema.Required, propName))
				fieldName := toFieldName(propName)
				jsonTag := propName
				if !isRequired(schema.Required, propName) {
					jsonTag += ",omitempty"
				}

				// Add field comment
				if propSchema.Description != "" {
					buf.WriteString(fmt.Sprintf("\t// %s\n", cleanDescription(propSchema.Description)))
				}

				buf.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", fieldName, goType, jsonTag))
			}
		}
		buf.WriteString("}\n")

	case "array":
		// Generate type alias for array
		itemType := "any"
		if schema.Items != nil {
			if itemSchema, ok := schema.Items.(*parser.Schema); ok {
				itemType = cg.schemaToGoType(itemSchema, true)
			}
		}
		buf.WriteString(fmt.Sprintf("type %s []%s\n", typeName, itemType))

	case "string":
		// Check for enum
		if len(schema.Enum) > 0 {
			buf.WriteString(fmt.Sprintf("type %s string\n\n", typeName))
			buf.WriteString("const (\n")
			for _, e := range schema.Enum {
				enumVal := fmt.Sprintf("%v", e)
				enumName := typeName + toFieldName(enumVal)
				buf.WriteString(fmt.Sprintf("\t%s %s = %q\n", enumName, typeName, enumVal))
			}
			buf.WriteString(")\n")
		} else {
			goType := stringFormatToGoType(schema.Format)
			buf.WriteString(fmt.Sprintf("type %s = %s\n", typeName, goType))
		}

	case "integer":
		goType := integerFormatToGoType(schema.Format)
		buf.WriteString(fmt.Sprintf("type %s = %s\n", typeName, goType))

	case "number":
		goType := numberFormatToGoType(schema.Format)
		buf.WriteString(fmt.Sprintf("type %s = %s\n", typeName, goType))

	case "boolean":
		buf.WriteString(fmt.Sprintf("type %s = bool\n", typeName))

	default:
		// Handle allOf
		if len(schema.AllOf) > 0 {
			return cg.generateAllOfType(typeName, schema)
		}
		// Default to any
		buf.WriteString(fmt.Sprintf("type %s = any\n", typeName))
	}

	return buf.String(), nil
}

// generateAllOfType generates a type for allOf composition
func (cg *oas2CodeGenerator) generateAllOfType(typeName string, schema *parser.Schema) (string, error) {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("// %s combines multiple schemas.\n", typeName))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", typeName))

	for _, subSchema := range schema.AllOf {
		if subSchema.Ref != "" {
			refType := cg.resolveRef(subSchema.Ref)
			buf.WriteString(fmt.Sprintf("\t%s\n", refType))
		} else if subSchema.Properties != nil {
			// Inline properties
			var propNames []string
			for propName := range subSchema.Properties {
				propNames = append(propNames, propName)
			}
			sort.Strings(propNames)

			for _, propName := range propNames {
				propSchema := subSchema.Properties[propName]
				if propSchema == nil {
					continue
				}
				goType := cg.schemaToGoType(propSchema, isRequired(subSchema.Required, propName))
				fieldName := toFieldName(propName)
				jsonTag := propName
				if !isRequired(subSchema.Required, propName) {
					jsonTag += ",omitempty"
				}
				buf.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", fieldName, goType, jsonTag))
			}
		}
	}

	buf.WriteString("}\n")
	return buf.String(), nil
}

// schemaToGoType converts a schema to a Go type string
func (cg *oas2CodeGenerator) schemaToGoType(schema *parser.Schema, required bool) string {
	if schema == nil {
		return "any"
	}

	// Handle $ref
	if schema.Ref != "" {
		refType := cg.resolveRef(schema.Ref)
		if !required && cg.g.UsePointers {
			return "*" + refType
		}
		return refType
	}

	schemaType := getSchemaType(schema)
	var goType string

	switch schemaType {
	case "string":
		goType = stringFormatToGoType(schema.Format)
	case "integer":
		goType = integerFormatToGoType(schema.Format)
	case "number":
		goType = numberFormatToGoType(schema.Format)
	case "boolean":
		goType = "bool"
	case "array":
		itemType := "any"
		if schema.Items != nil {
			if itemSchema, ok := schema.Items.(*parser.Schema); ok {
				itemType = cg.schemaToGoType(itemSchema, true)
			}
		}
		goType = "[]" + itemType
	case "object":
		if schema.Properties == nil && schema.AdditionalProperties != nil {
			// Map type
			valueType := "any"
			if addProps, ok := schema.AdditionalProperties.(*parser.Schema); ok {
				valueType = cg.schemaToGoType(addProps, true)
			}
			goType = "map[string]" + valueType
		} else {
			goType = "map[string]any"
		}
	default:
		goType = "any"
	}

	if !required && cg.g.UsePointers && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map") {
		return "*" + goType
	}

	return goType
}

// resolveRef resolves a $ref to a Go type name
func (cg *oas2CodeGenerator) resolveRef(ref string) string {
	if typeName, ok := cg.schemaNames[ref]; ok {
		return typeName
	}
	// Extract name from ref path
	parts := strings.Split(ref, "/")
	if len(parts) > 0 {
		return toTypeName(parts[len(parts)-1])
	}
	return "any"
}

// addIssue adds a generation issue
//
//nolint:unparam // severity parameter kept for API consistency and future extensibility
func (cg *oas2CodeGenerator) addIssue(path, message string, severity Severity) {
	cg.result.Issues = append(cg.result.Issues, GenerateIssue{
		Path:     path,
		Message:  message,
		Severity: severity,
	})
}

// generateClient generates HTTP client code for OAS 2.0
func (cg *oas2CodeGenerator) generateClient() error {
	var buf bytes.Buffer

	// Write header
	buf.WriteString("// Code generated by oastools. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", cg.result.PackageName))

	// Write imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"bytes\"\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"io\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString("\t\"strings\"\n")
	buf.WriteString(")\n\n")

	// Write client struct
	buf.WriteString("// Client is the API client.\n")
	buf.WriteString("type Client struct {\n")
	buf.WriteString("\t// BaseURL is the base URL for API requests.\n")
	buf.WriteString("\tBaseURL string\n")
	buf.WriteString("\t// HTTPClient is the HTTP client to use for requests.\n")
	buf.WriteString("\tHTTPClient *http.Client\n")
	buf.WriteString("\t// RequestEditors are functions that can modify requests before sending.\n")
	buf.WriteString("\tRequestEditors []RequestEditorFn\n")
	buf.WriteString("}\n\n")

	// Write types
	buf.WriteString("// RequestEditorFn is a function that can modify an HTTP request.\n")
	buf.WriteString("type RequestEditorFn func(ctx context.Context, req *http.Request) error\n\n")

	buf.WriteString("// ClientOption is a function that configures a Client.\n")
	buf.WriteString("type ClientOption func(*Client) error\n\n")

	// Write constructor
	buf.WriteString("// NewClient creates a new API client.\n")
	buf.WriteString("func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {\n")
	buf.WriteString("\tc := &Client{\n")
	buf.WriteString("\t\tBaseURL:    strings.TrimSuffix(baseURL, \"/\"),\n")
	buf.WriteString("\t\tHTTPClient: http.DefaultClient,\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tfor _, opt := range opts {\n")
	buf.WriteString("\t\tif err := opt(c); err != nil {\n")
	buf.WriteString("\t\t\treturn nil, err\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn c, nil\n")
	buf.WriteString("}\n\n")

	// Write client options
	buf.WriteString("// WithHTTPClient sets the HTTP client.\n")
	buf.WriteString("func WithHTTPClient(client *http.Client) ClientOption {\n")
	buf.WriteString("\treturn func(c *Client) error {\n")
	buf.WriteString("\t\tc.HTTPClient = client\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	buf.WriteString("// WithRequestEditor adds a request editor function.\n")
	buf.WriteString("func WithRequestEditor(fn RequestEditorFn) ClientOption {\n")
	buf.WriteString("\treturn func(c *Client) error {\n")
	buf.WriteString("\t\tc.RequestEditors = append(c.RequestEditors, fn)\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// Generate methods for each operation
	if cg.doc.Paths != nil {
		// Sort paths for deterministic output
		var pathKeys []string
		for path := range cg.doc.Paths {
			pathKeys = append(pathKeys, path)
		}
		sort.Strings(pathKeys)

		for _, path := range pathKeys {
			pathItem := cg.doc.Paths[path]
			if pathItem == nil {
				continue
			}

			operations := parser.GetOperations(pathItem, parser.OASVersion20)
			for _, method := range httpMethods {
				op := operations[method]
				if op == nil {
					continue
				}

				code, err := cg.generateClientMethod(path, method, op)
				if err != nil {
					cg.addIssue(fmt.Sprintf("paths.%s.%s", path, method), fmt.Sprintf("failed to generate client method: %v", err), SeverityWarning)
					continue
				}
				buf.WriteString(code)
				cg.result.GeneratedOperations++
			}
		}
	}

	// Write helper functions
	buf.WriteString(clientHelpers)

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		cg.addIssue("client.go", fmt.Sprintf("failed to format generated code: %v", err), SeverityWarning)
		formatted = buf.Bytes()
	}

	cg.result.Files = append(cg.result.Files, GeneratedFile{
		Name:    "client.go",
		Content: formatted,
	})

	return nil
}

// generateClientMethod generates a client method for an operation
//
//nolint:unparam // error return kept for API consistency with interface requirements
func (cg *oas2CodeGenerator) generateClientMethod(path, method string, op *parser.Operation) (string, error) {
	var buf bytes.Buffer

	methodName := operationToMethodName(op, path, method)

	// Build parameter list
	var params []string
	params = append(params, "ctx context.Context")

	// Path parameters
	var pathParams []pathParam
	for _, param := range op.Parameters {
		if param != nil && param.In == parser.ParamInPath {
			goType := cg.paramToGoType(param)
			paramName := toParamName(param.Name)
			params = append(params, fmt.Sprintf("%s %s", paramName, goType))
			pathParams = append(pathParams, pathParam{name: param.Name, varName: paramName})
		}
	}

	// Query parameters
	var queryParams []*parser.Parameter
	for _, param := range op.Parameters {
		if param != nil && param.In == parser.ParamInQuery {
			queryParams = append(queryParams, param)
		}
	}
	if len(queryParams) > 0 {
		params = append(params, "params *"+methodName+"Params")
	}

	// Request body (body parameter in OAS 2.0)
	var hasBody bool
	var bodyParamSchema *parser.Schema
	for _, param := range op.Parameters {
		if param != nil && param.In == parser.ParamInBody {
			hasBody = true
			bodyParamSchema = param.Schema
			break
		}
	}
	if hasBody {
		bodyType := "any"
		if bodyParamSchema != nil {
			bodyType = cg.schemaToGoType(bodyParamSchema, true)
		}
		params = append(params, "body "+bodyType)
	}

	// Write method documentation
	if op.Summary != "" {
		buf.WriteString(fmt.Sprintf("// %s %s\n", methodName, op.Summary))
	} else if op.Description != "" {
		buf.WriteString(fmt.Sprintf("// %s %s\n", methodName, cleanDescription(op.Description)))
	} else {
		buf.WriteString(fmt.Sprintf("// %s calls %s %s\n", methodName, strings.ToUpper(method), path))
	}
	if op.Deprecated {
		buf.WriteString("// Deprecated: This operation is deprecated.\n")
	}

	// Write method signature
	responseType := cg.getResponseType(op)
	buf.WriteString(fmt.Sprintf("func (c *Client) %s(%s) (%s, error) {\n", methodName, strings.Join(params, ", "), responseType))

	// Build URL
	buf.WriteString("\tpath := ")
	if len(pathParams) > 0 {
		buf.WriteString("fmt.Sprintf(\"")
		pathTemplate := path
		for _, pp := range pathParams {
			pathTemplate = strings.ReplaceAll(pathTemplate, "{"+pp.name+"}", "%v")
		}
		buf.WriteString(pathTemplate)
		buf.WriteString("\"")
		for _, pp := range pathParams {
			buf.WriteString(", " + pp.varName)
		}
		buf.WriteString(")\n")
	} else {
		buf.WriteString(fmt.Sprintf("%q\n", path))
	}

	// Build query string
	if len(queryParams) > 0 {
		buf.WriteString("\tquery := make(url.Values)\n")
		buf.WriteString("\tif params != nil {\n")
		for _, param := range queryParams {
			paramName := toFieldName(param.Name)
			if param.Required {
				buf.WriteString(fmt.Sprintf("\t\tquery.Set(%q, fmt.Sprintf(\"%%v\", params.%s))\n", param.Name, paramName))
			} else {
				buf.WriteString(fmt.Sprintf("\t\tif params.%s != nil {\n", paramName))
				buf.WriteString(fmt.Sprintf("\t\t\tquery.Set(%q, fmt.Sprintf(\"%%v\", *params.%s))\n", param.Name, paramName))
				buf.WriteString("\t\t}\n")
			}
		}
		buf.WriteString("\t}\n")
		buf.WriteString("\tif len(query) > 0 {\n")
		buf.WriteString("\t\tpath += \"?\" + query.Encode()\n")
		buf.WriteString("\t}\n")
	}

	// Create request
	if hasBody {
		buf.WriteString("\tbodyData, err := json.Marshal(body)\n")
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"marshal request body: %%w\", err)\n", zeroValue(responseType)))
		buf.WriteString("\t}\n")
		buf.WriteString(fmt.Sprintf("\treq, err := http.NewRequestWithContext(ctx, %q, c.BaseURL+path, bytes.NewReader(bodyData))\n", strings.ToUpper(method)))
	} else {
		buf.WriteString(fmt.Sprintf("\treq, err := http.NewRequestWithContext(ctx, %q, c.BaseURL+path, nil)\n", strings.ToUpper(method)))
	}
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"create request: %%w\", err)\n", zeroValue(responseType)))
	buf.WriteString("\t}\n")

	// Set content type
	if hasBody {
		buf.WriteString("\treq.Header.Set(\"Content-Type\", \"application/json\")\n")
	}
	buf.WriteString("\treq.Header.Set(\"Accept\", \"application/json\")\n")

	// Apply request editors
	buf.WriteString("\tfor _, editor := range c.RequestEditors {\n")
	buf.WriteString("\t\tif err := editor(ctx, req); err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\t\treturn %s, fmt.Errorf(\"request editor: %%w\", err)\n", zeroValue(responseType)))
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")

	// Execute request
	buf.WriteString("\tresp, err := c.HTTPClient.Do(req)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"execute request: %%w\", err)\n", zeroValue(responseType)))
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer resp.Body.Close()\n")

	// Handle response
	buf.WriteString("\tif resp.StatusCode >= 400 {\n")
	buf.WriteString("\t\tbody, _ := io.ReadAll(resp.Body)\n")
	buf.WriteString(fmt.Sprintf("\t\treturn %s, &APIError{StatusCode: resp.StatusCode, Body: body}\n", zeroValue(responseType)))
	buf.WriteString("\t}\n")

	// Parse response body
	if responseType != "" && responseType != "*http.Response" {
		if strings.HasPrefix(responseType, "*") {
			buf.WriteString(fmt.Sprintf("\tvar result %s\n", responseType[1:]))
			buf.WriteString("\tif err := json.NewDecoder(resp.Body).Decode(&result); err != nil {\n")
			buf.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"decode response: %%w\", err)\n", zeroValue(responseType)))
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &result, nil\n")
		} else {
			buf.WriteString(fmt.Sprintf("\tvar result %s\n", responseType))
			buf.WriteString("\tif err := json.NewDecoder(resp.Body).Decode(&result); err != nil {\n")
			buf.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"decode response: %%w\", err)\n", zeroValue(responseType)))
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn result, nil\n")
		}
	} else {
		buf.WriteString("\treturn resp, nil\n")
	}

	buf.WriteString("}\n\n")

	// Generate params struct if needed
	if len(queryParams) > 0 {
		buf.WriteString(fmt.Sprintf("// %sParams contains query parameters for %s.\n", methodName, methodName))
		buf.WriteString(fmt.Sprintf("type %sParams struct {\n", methodName))
		for _, param := range queryParams {
			goType := cg.paramToGoType(param)
			fieldName := toFieldName(param.Name)
			if param.Description != "" {
				buf.WriteString(fmt.Sprintf("\t// %s\n", cleanDescription(param.Description)))
			}
			if !param.Required {
				buf.WriteString(fmt.Sprintf("\t%s *%s `json:%q`\n", fieldName, goType, param.Name+",omitempty"))
			} else {
				buf.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", fieldName, goType, param.Name))
			}
		}
		buf.WriteString("}\n\n")
	}

	return buf.String(), nil
}

// paramToGoType converts a parameter to its Go type
func (cg *oas2CodeGenerator) paramToGoType(param *parser.Parameter) string {
	// OAS 2.0 uses type directly on parameter
	switch param.Type {
	case "string":
		return stringFormatToGoType(param.Format)
	case "integer":
		return integerFormatToGoType(param.Format)
	case "number":
		return numberFormatToGoType(param.Format)
	case "boolean":
		return "bool"
	case "array":
		return "[]string"
	default:
		return "string"
	}
}

// getResponseType determines the Go type for the success response
func (cg *oas2CodeGenerator) getResponseType(op *parser.Operation) string {
	if op.Responses == nil {
		return "*http.Response"
	}

	// Check for 200, 201 responses
	for _, code := range []string{"200", "201"} {
		if resp := op.Responses.Codes[code]; resp != nil {
			// OAS 2.0 uses schema directly on response
			if resp.Schema != nil {
				goType := cg.schemaToGoType(resp.Schema, true)
				if !strings.HasPrefix(goType, "*") && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map") {
					return "*" + goType
				}
				return goType
			}
		}
	}

	// Check default response
	if op.Responses.Default != nil && op.Responses.Default.Schema != nil {
		goType := cg.schemaToGoType(op.Responses.Default.Schema, true)
		if !strings.HasPrefix(goType, "*") && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map") {
			return "*" + goType
		}
		return goType
	}

	return "*http.Response"
}

// generateServer generates server interface code for OAS 2.0
func (cg *oas2CodeGenerator) generateServer() error {
	var buf bytes.Buffer

	// Write header
	buf.WriteString("// Code generated by oastools. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", cg.result.PackageName))

	// Write imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString(")\n\n")

	// Generate server interface
	buf.WriteString("// ServerInterface represents the server API.\n")
	buf.WriteString("type ServerInterface interface {\n")

	if cg.doc.Paths != nil {
		// Sort paths for deterministic output
		var pathKeys []string
		for path := range cg.doc.Paths {
			pathKeys = append(pathKeys, path)
		}
		sort.Strings(pathKeys)

		for _, path := range pathKeys {
			pathItem := cg.doc.Paths[path]
			if pathItem == nil {
				continue
			}

			operations := parser.GetOperations(pathItem, parser.OASVersion20)
			for _, method := range httpMethods {
				op := operations[method]
				if op == nil {
					continue
				}

				sig := cg.generateServerMethodSignature(path, method, op)
				buf.WriteString(sig)
			}
		}
	}

	buf.WriteString("}\n\n")

	// Generate request types
	for _, path := range func() []string {
		var keys []string
		if cg.doc.Paths != nil {
			for k := range cg.doc.Paths {
				keys = append(keys, k)
			}
		}
		sort.Strings(keys)
		return keys
	}() {
		pathItem := cg.doc.Paths[path]
		if pathItem == nil {
			continue
		}

		operations := parser.GetOperations(pathItem, parser.OASVersion20)
		for _, method := range httpMethods {
			op := operations[method]
			if op == nil {
				continue
			}

			reqType := cg.generateRequestType(path, method, op)
			if reqType != "" {
				buf.WriteString(reqType)
			}
		}
	}

	// Write unimplemented server
	buf.WriteString("// UnimplementedServer provides default implementations that return errors.\n")
	buf.WriteString("type UnimplementedServer struct{}\n\n")

	// Generate unimplemented methods
	if cg.doc.Paths != nil {
		var pathKeys []string
		for path := range cg.doc.Paths {
			pathKeys = append(pathKeys, path)
		}
		sort.Strings(pathKeys)

		for _, path := range pathKeys {
			pathItem := cg.doc.Paths[path]
			if pathItem == nil {
				continue
			}

			operations := parser.GetOperations(pathItem, parser.OASVersion20)
			for _, method := range httpMethods {
				op := operations[method]
				if op == nil {
					continue
				}

				methodName := operationToMethodName(op, path, method)
				responseType := cg.getResponseType(op)

				buf.WriteString(fmt.Sprintf("func (s *UnimplementedServer) %s(ctx context.Context, req *%sRequest) (%s, error) {\n",
					methodName, methodName, responseType))
				buf.WriteString(fmt.Sprintf("\treturn %s, ErrNotImplemented\n", zeroValue(responseType)))
				buf.WriteString("}\n\n")
			}
		}
	}

	// Write error type
	buf.WriteString("// ErrNotImplemented is returned by UnimplementedServer methods.\n")
	buf.WriteString("var ErrNotImplemented = &NotImplementedError{}\n\n")
	buf.WriteString("// NotImplementedError indicates an operation is not implemented.\n")
	buf.WriteString("type NotImplementedError struct{}\n\n")
	buf.WriteString("func (e *NotImplementedError) Error() string { return \"not implemented\" }\n\n")

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		cg.addIssue("server.go", fmt.Sprintf("failed to format generated code: %v", err), SeverityWarning)
		formatted = buf.Bytes()
	}

	cg.result.Files = append(cg.result.Files, GeneratedFile{
		Name:    "server.go",
		Content: formatted,
	})

	return nil
}

// generateServerMethodSignature generates the interface method signature
func (cg *oas2CodeGenerator) generateServerMethodSignature(path, method string, op *parser.Operation) string {
	var buf bytes.Buffer

	methodName := operationToMethodName(op, path, method)
	responseType := cg.getResponseType(op)

	// Write comment
	if op.Summary != "" {
		buf.WriteString(fmt.Sprintf("\t// %s %s\n", methodName, op.Summary))
	}
	if op.Deprecated {
		buf.WriteString("\t// Deprecated: This operation is deprecated.\n")
	}

	buf.WriteString(fmt.Sprintf("\t%s(ctx context.Context, req *%sRequest) (%s, error)\n", methodName, methodName, responseType))

	return buf.String()
}

// generateRequestType generates a request struct for an operation
func (cg *oas2CodeGenerator) generateRequestType(path, method string, op *parser.Operation) string {
	var buf bytes.Buffer

	methodName := operationToMethodName(op, path, method)

	buf.WriteString(fmt.Sprintf("// %sRequest contains the request data for %s.\n", methodName, methodName))
	buf.WriteString(fmt.Sprintf("type %sRequest struct {\n", methodName))

	// Path parameters
	for _, param := range op.Parameters {
		if param != nil && param.In == parser.ParamInPath {
			goType := cg.paramToGoType(param)
			fieldName := toFieldName(param.Name)
			buf.WriteString(fmt.Sprintf("\t%s %s\n", fieldName, goType))
		}
	}

	// Query parameters
	for _, param := range op.Parameters {
		if param != nil && param.In == parser.ParamInQuery {
			goType := cg.paramToGoType(param)
			fieldName := toFieldName(param.Name)
			if !param.Required {
				buf.WriteString(fmt.Sprintf("\t%s *%s\n", fieldName, goType))
			} else {
				buf.WriteString(fmt.Sprintf("\t%s %s\n", fieldName, goType))
			}
		}
	}

	// Header parameters
	for _, param := range op.Parameters {
		if param != nil && param.In == parser.ParamInHeader {
			goType := cg.paramToGoType(param)
			fieldName := toFieldName(param.Name)
			if !param.Required {
				buf.WriteString(fmt.Sprintf("\t%s *%s\n", fieldName, goType))
			} else {
				buf.WriteString(fmt.Sprintf("\t%s %s\n", fieldName, goType))
			}
		}
	}

	// Body parameter (OAS 2.0)
	for _, param := range op.Parameters {
		if param != nil && param.In == parser.ParamInBody {
			bodyType := "any"
			if param.Schema != nil {
				bodyType = cg.schemaToGoType(param.Schema, true)
			}
			buf.WriteString(fmt.Sprintf("\tBody %s\n", bodyType))
			break
		}
	}

	// HTTP request
	buf.WriteString("\tHTTPRequest *http.Request\n")

	buf.WriteString("}\n\n")

	return buf.String()
}
