coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "diff, flags, files"
  behavior: default

