coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 5%

# Ignore CLI entry point from patch coverage - CLI handlers are integration-tested
# via actual CLI usage, not unit tests. Library code in packages is fully tested.
ignore:
  - "cmd/**/*"

comment:
  layout: "diff, flags, files"
  behavior: default

