version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - cyclop
    - unparam
  settings:
    cyclop:
      max-complexity: 50
    staticcheck:
      checks:
        - "all"
        - "-SA5011"  # Disable false positives for nil checks followed by t.Fatal()

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
