version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - cyclop
    - unparam
  settings:
    cyclop:
      max-complexity: 50

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
