// Code generated by oastools. DO NOT EDIT.

package petstore

import (
	"context"
	"net/http"
)

// Security scheme helpers
// These ClientOption functions configure authentication for API requests.

// WithApiKeyAPIKey sets the api_key header for API key authentication.
// API key authentication via header
func WithApiKeyAPIKey(key string) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, func(ctx context.Context, req *http.Request) error {
			req.Header.Set("api_key", key)
			return nil
		})
		return nil
	}
}

// WithPetstoreAuthOAuth2Token sets the OAuth2 bearer token for authentication.
// Available scopes: read:pets, write:pets
func WithPetstoreAuthOAuth2Token(token string) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, func(ctx context.Context, req *http.Request) error {
			req.Header.Set("Authorization", "Bearer "+token)
			return nil
		})
		return nil
	}
}
