// Code generated by oastools. DO NOT EDIT.

package petstore

import (
	"encoding/json"
	"net/http"
)

// WriteJSON writes a JSON response with the given status code
func WriteJSON(w http.ResponseWriter, statusCode int, body any) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(statusCode)
	if body != nil {
		return json.NewEncoder(w).Encode(body)
	}
	return nil
}

// WriteError writes a JSON error response
func WriteError(w http.ResponseWriter, statusCode int, message string) error {
	return WriteJSON(w, statusCode, map[string]string{"error": message})
}

// WriteNoContent writes a 204 No Content response
func WriteNoContent(w http.ResponseWriter) {
	w.WriteHeader(http.StatusNoContent)
}

// UpdatePetResponse encapsulates possible responses for UpdatePet.
type UpdatePetResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r UpdatePetResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r UpdatePetResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r UpdatePetResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r UpdatePetResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status400 creates a 400 response - Invalid ID supplied.
func (UpdatePetResponse) Status400() UpdatePetResponse {
	return UpdatePetResponse{
		statusCode: 400,
	}
}

// Status404 creates a 404 response - Pet not found.
func (UpdatePetResponse) Status404() UpdatePetResponse {
	return UpdatePetResponse{
		statusCode: 404,
	}
}

// Status405 creates a 405 response - Validation exception.
func (UpdatePetResponse) Status405() UpdatePetResponse {
	return UpdatePetResponse{
		statusCode: 405,
	}
}

// AddPetResponse encapsulates possible responses for AddPet.
type AddPetResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r AddPetResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r AddPetResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r AddPetResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r AddPetResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status405 creates a 405 response - Invalid input.
func (AddPetResponse) Status405() AddPetResponse {
	return AddPetResponse{
		statusCode: 405,
	}
}

// FindPetsByStatusResponse encapsulates possible responses for FindPetsByStatus.
type FindPetsByStatusResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r FindPetsByStatusResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r FindPetsByStatusResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r FindPetsByStatusResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r FindPetsByStatusResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (FindPetsByStatusResponse) Status200(body []Pet) FindPetsByStatusResponse {
	return FindPetsByStatusResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// Status400 creates a 400 response - Invalid status value.
func (FindPetsByStatusResponse) Status400() FindPetsByStatusResponse {
	return FindPetsByStatusResponse{
		statusCode: 400,
	}
}

// FindPetsByTagsResponse encapsulates possible responses for FindPetsByTags.
type FindPetsByTagsResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r FindPetsByTagsResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r FindPetsByTagsResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r FindPetsByTagsResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r FindPetsByTagsResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (FindPetsByTagsResponse) Status200(body []Pet) FindPetsByTagsResponse {
	return FindPetsByTagsResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// Status400 creates a 400 response - Invalid tag value.
func (FindPetsByTagsResponse) Status400() FindPetsByTagsResponse {
	return FindPetsByTagsResponse{
		statusCode: 400,
	}
}

// GetPetByIdResponse encapsulates possible responses for GetPetById.
type GetPetByIdResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r GetPetByIdResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r GetPetByIdResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r GetPetByIdResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r GetPetByIdResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (GetPetByIdResponse) Status200(body Pet) GetPetByIdResponse {
	return GetPetByIdResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// Status400 creates a 400 response - Invalid ID supplied.
func (GetPetByIdResponse) Status400() GetPetByIdResponse {
	return GetPetByIdResponse{
		statusCode: 400,
	}
}

// Status404 creates a 404 response - Pet not found.
func (GetPetByIdResponse) Status404() GetPetByIdResponse {
	return GetPetByIdResponse{
		statusCode: 404,
	}
}

// UpdatePetWithFormResponse encapsulates possible responses for UpdatePetWithForm.
type UpdatePetWithFormResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r UpdatePetWithFormResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r UpdatePetWithFormResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r UpdatePetWithFormResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r UpdatePetWithFormResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status405 creates a 405 response - Invalid input.
func (UpdatePetWithFormResponse) Status405() UpdatePetWithFormResponse {
	return UpdatePetWithFormResponse{
		statusCode: 405,
	}
}

// DeletePetResponse encapsulates possible responses for DeletePet.
type DeletePetResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r DeletePetResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r DeletePetResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r DeletePetResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r DeletePetResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status400 creates a 400 response - Invalid ID supplied.
func (DeletePetResponse) Status400() DeletePetResponse {
	return DeletePetResponse{
		statusCode: 400,
	}
}

// Status404 creates a 404 response - Pet not found.
func (DeletePetResponse) Status404() DeletePetResponse {
	return DeletePetResponse{
		statusCode: 404,
	}
}

// UploadFileResponse encapsulates possible responses for UploadFile.
type UploadFileResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r UploadFileResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r UploadFileResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r UploadFileResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r UploadFileResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (UploadFileResponse) Status200(body ApiResponse) UploadFileResponse {
	return UploadFileResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// GetInventoryResponse encapsulates possible responses for GetInventory.
type GetInventoryResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r GetInventoryResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r GetInventoryResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r GetInventoryResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r GetInventoryResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (GetInventoryResponse) Status200(body map[string]int32) GetInventoryResponse {
	return GetInventoryResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// PlaceOrderResponse encapsulates possible responses for PlaceOrder.
type PlaceOrderResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r PlaceOrderResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r PlaceOrderResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r PlaceOrderResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r PlaceOrderResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (PlaceOrderResponse) Status200(body Order) PlaceOrderResponse {
	return PlaceOrderResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// Status400 creates a 400 response - Invalid Order.
func (PlaceOrderResponse) Status400() PlaceOrderResponse {
	return PlaceOrderResponse{
		statusCode: 400,
	}
}

// GetOrderByIdResponse encapsulates possible responses for GetOrderById.
type GetOrderByIdResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r GetOrderByIdResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r GetOrderByIdResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r GetOrderByIdResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r GetOrderByIdResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (GetOrderByIdResponse) Status200(body Order) GetOrderByIdResponse {
	return GetOrderByIdResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// Status400 creates a 400 response - Invalid ID supplied.
func (GetOrderByIdResponse) Status400() GetOrderByIdResponse {
	return GetOrderByIdResponse{
		statusCode: 400,
	}
}

// Status404 creates a 404 response - Order not found.
func (GetOrderByIdResponse) Status404() GetOrderByIdResponse {
	return GetOrderByIdResponse{
		statusCode: 404,
	}
}

// DeleteOrderResponse encapsulates possible responses for DeleteOrder.
type DeleteOrderResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r DeleteOrderResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r DeleteOrderResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r DeleteOrderResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r DeleteOrderResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status400 creates a 400 response - Invalid ID supplied.
func (DeleteOrderResponse) Status400() DeleteOrderResponse {
	return DeleteOrderResponse{
		statusCode: 400,
	}
}

// Status404 creates a 404 response - Order not found.
func (DeleteOrderResponse) Status404() DeleteOrderResponse {
	return DeleteOrderResponse{
		statusCode: 404,
	}
}

// CreateUserResponse encapsulates possible responses for CreateUser.
type CreateUserResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r CreateUserResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r CreateUserResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r CreateUserResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r CreateUserResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// StatusDefault creates a default response - successful operation.
func (CreateUserResponse) StatusDefault() CreateUserResponse {
	return CreateUserResponse{
		statusCode: 500,
	}
}

// CreateUsersWithArrayInputResponse encapsulates possible responses for CreateUsersWithArrayInput.
type CreateUsersWithArrayInputResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r CreateUsersWithArrayInputResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r CreateUsersWithArrayInputResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r CreateUsersWithArrayInputResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r CreateUsersWithArrayInputResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// StatusDefault creates a default response - successful operation.
func (CreateUsersWithArrayInputResponse) StatusDefault() CreateUsersWithArrayInputResponse {
	return CreateUsersWithArrayInputResponse{
		statusCode: 500,
	}
}

// CreateUsersWithListInputResponse encapsulates possible responses for CreateUsersWithListInput.
type CreateUsersWithListInputResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r CreateUsersWithListInputResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r CreateUsersWithListInputResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r CreateUsersWithListInputResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r CreateUsersWithListInputResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// StatusDefault creates a default response - successful operation.
func (CreateUsersWithListInputResponse) StatusDefault() CreateUsersWithListInputResponse {
	return CreateUsersWithListInputResponse{
		statusCode: 500,
	}
}

// LoginUserResponse encapsulates possible responses for LoginUser.
type LoginUserResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r LoginUserResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r LoginUserResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r LoginUserResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r LoginUserResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (LoginUserResponse) Status200(body string) LoginUserResponse {
	return LoginUserResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// Status400 creates a 400 response - Invalid username/password supplied.
func (LoginUserResponse) Status400() LoginUserResponse {
	return LoginUserResponse{
		statusCode: 400,
	}
}

// LogoutUserResponse encapsulates possible responses for LogoutUser.
type LogoutUserResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r LogoutUserResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r LogoutUserResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r LogoutUserResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r LogoutUserResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// StatusDefault creates a default response - successful operation.
func (LogoutUserResponse) StatusDefault() LogoutUserResponse {
	return LogoutUserResponse{
		statusCode: 500,
	}
}

// GetUserByNameResponse encapsulates possible responses for GetUserByName.
type GetUserByNameResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r GetUserByNameResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r GetUserByNameResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r GetUserByNameResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r GetUserByNameResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status200 creates a 200 response - successful operation.
func (GetUserByNameResponse) Status200(body User) GetUserByNameResponse {
	return GetUserByNameResponse{
		statusCode:  200,
		body:        body,
		contentType: "application/json",
	}
}

// Status400 creates a 400 response - Invalid username supplied.
func (GetUserByNameResponse) Status400() GetUserByNameResponse {
	return GetUserByNameResponse{
		statusCode: 400,
	}
}

// Status404 creates a 404 response - User not found.
func (GetUserByNameResponse) Status404() GetUserByNameResponse {
	return GetUserByNameResponse{
		statusCode: 404,
	}
}

// UpdateUserResponse encapsulates possible responses for UpdateUser.
type UpdateUserResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r UpdateUserResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r UpdateUserResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r UpdateUserResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r UpdateUserResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status400 creates a 400 response - Invalid user supplied.
func (UpdateUserResponse) Status400() UpdateUserResponse {
	return UpdateUserResponse{
		statusCode: 400,
	}
}

// Status404 creates a 404 response - User not found.
func (UpdateUserResponse) Status404() UpdateUserResponse {
	return UpdateUserResponse{
		statusCode: 404,
	}
}

// DeleteUserResponse encapsulates possible responses for DeleteUser.
type DeleteUserResponse struct {
	statusCode  int
	body        any
	contentType string
}

// StatusCode returns the HTTP status code for this response.
func (r DeleteUserResponse) StatusCode() int { return r.statusCode }

// Body returns the response body.
func (r DeleteUserResponse) Body() any { return r.body }

// ContentType returns the Content-Type header value.
func (r DeleteUserResponse) ContentType() string {
	if r.contentType != "" {
		return r.contentType
	}
	return "application/json"
}

// WriteTo writes the response to the http.ResponseWriter.
func (r DeleteUserResponse) WriteTo(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", r.ContentType())
	w.WriteHeader(r.statusCode)
	if r.body != nil {
		return json.NewEncoder(w).Encode(r.body)
	}
	return nil
}

// Status400 creates a 400 response - Invalid username supplied.
func (DeleteUserResponse) Status400() DeleteUserResponse {
	return DeleteUserResponse{
		statusCode: 400,
	}
}

// Status404 creates a 404 response - User not found.
func (DeleteUserResponse) Status404() DeleteUserResponse {
	return DeleteUserResponse{
		statusCode: 404,
	}
}
