// Code generated by oastools. DO NOT EDIT.

package petstore

import (
	"fmt"
	"net/http"

	"github.com/erraggy/oastools/httpvalidator"
	"github.com/erraggy/oastools/parser"
)

// RequestBinder validates and binds HTTP requests to typed request structs.
type RequestBinder struct {
	validator *httpvalidator.Validator
}

// NewRequestBinder creates a new RequestBinder from a parsed OpenAPI specification.
func NewRequestBinder(parsed *parser.ParseResult) (*RequestBinder, error) {
	v, err := httpvalidator.New(parsed)
	if err != nil {
		return nil, fmt.Errorf("failed to create validator: %w", err)
	}
	return &RequestBinder{validator: v}, nil
}

// NewRequestBinderFromValidator creates a new RequestBinder from an existing validator.
func NewRequestBinderFromValidator(v *httpvalidator.Validator) *RequestBinder {
	return &RequestBinder{validator: v}
}

// BindingError represents a request binding failure.
type BindingError struct {
	ValidationResult *httpvalidator.RequestValidationResult
	Message          string
}

func (e *BindingError) Error() string {
	if e.Message != "" {
		return e.Message
	}
	if e.ValidationResult != nil && len(e.ValidationResult.Errors) > 0 {
		return e.ValidationResult.Errors[0].Message
	}
	return "request binding failed"
}

// ValidationErrors returns the validation errors if any.
func (e *BindingError) ValidationErrors() []httpvalidator.ValidationError {
	if e.ValidationResult != nil {
		return e.ValidationResult.Errors
	}
	return nil
}

// BindUpdatePetRequest validates and binds an HTTP request to a UpdatePetRequest.
func (b *RequestBinder) BindUpdatePetRequest(r *http.Request) (*UpdatePetRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &UpdatePetRequest{
		HTTPRequest: r,
	}

	return req, nil
}

// BindAddPetRequest validates and binds an HTTP request to a AddPetRequest.
func (b *RequestBinder) BindAddPetRequest(r *http.Request) (*AddPetRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &AddPetRequest{
		HTTPRequest: r,
	}

	return req, nil
}

// BindFindPetsByStatusRequest validates and binds an HTTP request to a FindPetsByStatusRequest.
func (b *RequestBinder) BindFindPetsByStatusRequest(r *http.Request) (*FindPetsByStatusRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &FindPetsByStatusRequest{
		HTTPRequest: r,
	}

	// Bind query parameter: status
	if v, ok := result.QueryParams["status"]; ok && v != nil {
		if val, ok := v.([]any); ok {
			arr := make([]string, len(val))
			for i, item := range val {
				if s, ok := item.(string); ok {
					arr[i] = s
				}
			}
			req.Status = arr
		}
	}

	return req, nil
}

// BindFindPetsByTagsRequest validates and binds an HTTP request to a FindPetsByTagsRequest.
func (b *RequestBinder) BindFindPetsByTagsRequest(r *http.Request) (*FindPetsByTagsRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &FindPetsByTagsRequest{
		HTTPRequest: r,
	}

	// Bind query parameter: tags
	if v, ok := result.QueryParams["tags"]; ok && v != nil {
		if val, ok := v.([]any); ok {
			arr := make([]string, len(val))
			for i, item := range val {
				if s, ok := item.(string); ok {
					arr[i] = s
				}
			}
			req.Tags = arr
		}
	}

	return req, nil
}

// BindGetPetByIdRequest validates and binds an HTTP request to a GetPetByIdRequest.
func (b *RequestBinder) BindGetPetByIdRequest(r *http.Request) (*GetPetByIdRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &GetPetByIdRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: petId
	if v, ok := result.PathParams["petId"]; ok {
		if val, ok := v.(float64); ok {
			req.PetId = int64(val)
		} else if val, ok := v.(int); ok {
			req.PetId = int64(val)
		} else if val, ok := v.(int64); ok {
			req.PetId = int64(val)
		}
	}

	return req, nil
}

// BindUpdatePetWithFormRequest validates and binds an HTTP request to a UpdatePetWithFormRequest.
func (b *RequestBinder) BindUpdatePetWithFormRequest(r *http.Request) (*UpdatePetWithFormRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &UpdatePetWithFormRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: petId
	if v, ok := result.PathParams["petId"]; ok {
		if val, ok := v.(float64); ok {
			req.PetId = int64(val)
		} else if val, ok := v.(int); ok {
			req.PetId = int64(val)
		} else if val, ok := v.(int64); ok {
			req.PetId = int64(val)
		}
	}

	return req, nil
}

// BindDeletePetRequest validates and binds an HTTP request to a DeletePetRequest.
func (b *RequestBinder) BindDeletePetRequest(r *http.Request) (*DeletePetRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &DeletePetRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: petId
	if v, ok := result.PathParams["petId"]; ok {
		if val, ok := v.(float64); ok {
			req.PetId = int64(val)
		} else if val, ok := v.(int); ok {
			req.PetId = int64(val)
		} else if val, ok := v.(int64); ok {
			req.PetId = int64(val)
		}
	}

	// Bind header parameter: api_key
	if v, ok := result.HeaderParams["api_key"]; ok && v != nil {
		if val, ok := v.(string); ok {
			req.ApiKey = &val
		}
	}

	return req, nil
}

// BindUploadFileRequest validates and binds an HTTP request to a UploadFileRequest.
func (b *RequestBinder) BindUploadFileRequest(r *http.Request) (*UploadFileRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &UploadFileRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: petId
	if v, ok := result.PathParams["petId"]; ok {
		if val, ok := v.(float64); ok {
			req.PetId = int64(val)
		} else if val, ok := v.(int); ok {
			req.PetId = int64(val)
		} else if val, ok := v.(int64); ok {
			req.PetId = int64(val)
		}
	}

	return req, nil
}

// BindGetInventoryRequest validates and binds an HTTP request to a GetInventoryRequest.
func (b *RequestBinder) BindGetInventoryRequest(r *http.Request) (*GetInventoryRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &GetInventoryRequest{
		HTTPRequest: r,
	}

	return req, nil
}

// BindPlaceOrderRequest validates and binds an HTTP request to a PlaceOrderRequest.
func (b *RequestBinder) BindPlaceOrderRequest(r *http.Request) (*PlaceOrderRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &PlaceOrderRequest{
		HTTPRequest: r,
	}

	return req, nil
}

// BindGetOrderByIdRequest validates and binds an HTTP request to a GetOrderByIdRequest.
func (b *RequestBinder) BindGetOrderByIdRequest(r *http.Request) (*GetOrderByIdRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &GetOrderByIdRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: orderId
	if v, ok := result.PathParams["orderId"]; ok {
		if val, ok := v.(float64); ok {
			req.OrderId = int64(val)
		} else if val, ok := v.(int); ok {
			req.OrderId = int64(val)
		} else if val, ok := v.(int64); ok {
			req.OrderId = int64(val)
		}
	}

	return req, nil
}

// BindDeleteOrderRequest validates and binds an HTTP request to a DeleteOrderRequest.
func (b *RequestBinder) BindDeleteOrderRequest(r *http.Request) (*DeleteOrderRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &DeleteOrderRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: orderId
	if v, ok := result.PathParams["orderId"]; ok {
		if val, ok := v.(float64); ok {
			req.OrderId = int64(val)
		} else if val, ok := v.(int); ok {
			req.OrderId = int64(val)
		} else if val, ok := v.(int64); ok {
			req.OrderId = int64(val)
		}
	}

	return req, nil
}

// BindCreateUserRequest validates and binds an HTTP request to a CreateUserRequest.
func (b *RequestBinder) BindCreateUserRequest(r *http.Request) (*CreateUserRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &CreateUserRequest{
		HTTPRequest: r,
	}

	return req, nil
}

// BindCreateUsersWithArrayInputRequest validates and binds an HTTP request to a CreateUsersWithArrayInputRequest.
func (b *RequestBinder) BindCreateUsersWithArrayInputRequest(r *http.Request) (*CreateUsersWithArrayInputRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &CreateUsersWithArrayInputRequest{
		HTTPRequest: r,
	}

	return req, nil
}

// BindCreateUsersWithListInputRequest validates and binds an HTTP request to a CreateUsersWithListInputRequest.
func (b *RequestBinder) BindCreateUsersWithListInputRequest(r *http.Request) (*CreateUsersWithListInputRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &CreateUsersWithListInputRequest{
		HTTPRequest: r,
	}

	return req, nil
}

// BindLoginUserRequest validates and binds an HTTP request to a LoginUserRequest.
func (b *RequestBinder) BindLoginUserRequest(r *http.Request) (*LoginUserRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &LoginUserRequest{
		HTTPRequest: r,
	}

	// Bind query parameter: username
	if v, ok := result.QueryParams["username"]; ok && v != nil {
		if val, ok := v.(string); ok {
			req.Username = val
		}
	}

	// Bind query parameter: password
	if v, ok := result.QueryParams["password"]; ok && v != nil {
		if val, ok := v.(string); ok {
			req.Password = val
		}
	}

	return req, nil
}

// BindLogoutUserRequest validates and binds an HTTP request to a LogoutUserRequest.
func (b *RequestBinder) BindLogoutUserRequest(r *http.Request) (*LogoutUserRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &LogoutUserRequest{
		HTTPRequest: r,
	}

	return req, nil
}

// BindGetUserByNameRequest validates and binds an HTTP request to a GetUserByNameRequest.
func (b *RequestBinder) BindGetUserByNameRequest(r *http.Request) (*GetUserByNameRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &GetUserByNameRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: username
	if v, ok := result.PathParams["username"]; ok {
		if val, ok := v.(string); ok {
			req.Username = val
		}
	}

	return req, nil
}

// BindUpdateUserRequest validates and binds an HTTP request to a UpdateUserRequest.
func (b *RequestBinder) BindUpdateUserRequest(r *http.Request) (*UpdateUserRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &UpdateUserRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: username
	if v, ok := result.PathParams["username"]; ok {
		if val, ok := v.(string); ok {
			req.Username = val
		}
	}

	return req, nil
}

// BindDeleteUserRequest validates and binds an HTTP request to a DeleteUserRequest.
func (b *RequestBinder) BindDeleteUserRequest(r *http.Request) (*DeleteUserRequest, error) {
	result, err := b.validator.ValidateRequest(r)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, &BindingError{ValidationResult: result}
	}

	req := &DeleteUserRequest{
		HTTPRequest: r,
	}

	// Bind path parameter: username
	if v, ok := result.PathParams["username"]; ok {
		if val, ok := v.(string); ok {
			req.Username = val
		}
	}

	return req, nil
}
