// Code generated by oastools. DO NOT EDIT.

package petstore

import (
	"context"
	"net/http"
)

// ServerInterface represents the server API.
type ServerInterface interface {
	// UpdatePet Update an existing pet
	UpdatePet(ctx context.Context, req *UpdatePetRequest) (*http.Response, error)
	// AddPet Add a new pet to the store
	AddPet(ctx context.Context, req *AddPetRequest) (*http.Response, error)
	// FindPetsByStatus Finds Pets by status
	FindPetsByStatus(ctx context.Context, req *FindPetsByStatusRequest) ([]Pet, error)
	// FindPetsByTags Finds Pets by tags
	// Deprecated: This operation is deprecated.
	FindPetsByTags(ctx context.Context, req *FindPetsByTagsRequest) ([]Pet, error)
	// GetPetById Find pet by ID
	GetPetById(ctx context.Context, req *GetPetByIdRequest) (*Pet, error)
	// UpdatePetWithForm Updates a pet in the store with form data
	UpdatePetWithForm(ctx context.Context, req *UpdatePetWithFormRequest) (*http.Response, error)
	// DeletePet Deletes a pet
	DeletePet(ctx context.Context, req *DeletePetRequest) (*http.Response, error)
	// UploadFile uploads an image
	UploadFile(ctx context.Context, req *UploadFileRequest) (*ApiResponse, error)
	// GetInventory Returns pet inventories by status
	GetInventory(ctx context.Context, req *GetInventoryRequest) (map[string]int32, error)
	// PlaceOrder Place an order for a pet
	PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*Order, error)
	// GetOrderById Find purchase order by ID
	GetOrderById(ctx context.Context, req *GetOrderByIdRequest) (*Order, error)
	// DeleteOrder Delete purchase order by ID
	DeleteOrder(ctx context.Context, req *DeleteOrderRequest) (*http.Response, error)
	// CreateUser Create user
	CreateUser(ctx context.Context, req *CreateUserRequest) (*http.Response, error)
	// CreateUsersWithArrayInput Creates list of users with given input array
	CreateUsersWithArrayInput(ctx context.Context, req *CreateUsersWithArrayInputRequest) (*http.Response, error)
	// CreateUsersWithListInput Creates list of users with given input array
	CreateUsersWithListInput(ctx context.Context, req *CreateUsersWithListInputRequest) (*http.Response, error)
	// LoginUser Logs user into the system
	LoginUser(ctx context.Context, req *LoginUserRequest) (*string, error)
	// LogoutUser Logs out current logged in user session
	LogoutUser(ctx context.Context, req *LogoutUserRequest) (*http.Response, error)
	// GetUserByName Get user by user name
	GetUserByName(ctx context.Context, req *GetUserByNameRequest) (*User, error)
	// UpdateUser Updated user
	UpdateUser(ctx context.Context, req *UpdateUserRequest) (*http.Response, error)
	// DeleteUser Delete user
	DeleteUser(ctx context.Context, req *DeleteUserRequest) (*http.Response, error)
}

// UpdatePetRequest contains the request data for UpdatePet.
type UpdatePetRequest struct {
	Body        Pet
	HTTPRequest *http.Request
}

// AddPetRequest contains the request data for AddPet.
type AddPetRequest struct {
	Body        Pet
	HTTPRequest *http.Request
}

// FindPetsByStatusRequest contains the request data for FindPetsByStatus.
type FindPetsByStatusRequest struct {
	Status      []string
	HTTPRequest *http.Request
}

// FindPetsByTagsRequest contains the request data for FindPetsByTags.
type FindPetsByTagsRequest struct {
	Tags        []string
	HTTPRequest *http.Request
}

// GetPetByIdRequest contains the request data for GetPetById.
type GetPetByIdRequest struct {
	PetId       int64
	HTTPRequest *http.Request
}

// UpdatePetWithFormRequest contains the request data for UpdatePetWithForm.
type UpdatePetWithFormRequest struct {
	PetId       int64
	HTTPRequest *http.Request
}

// DeletePetRequest contains the request data for DeletePet.
type DeletePetRequest struct {
	PetId       int64
	ApiKey      *string
	HTTPRequest *http.Request
}

// UploadFileRequest contains the request data for UploadFile.
type UploadFileRequest struct {
	PetId       int64
	HTTPRequest *http.Request
}

// GetInventoryRequest contains the request data for GetInventory.
type GetInventoryRequest struct {
	HTTPRequest *http.Request
}

// PlaceOrderRequest contains the request data for PlaceOrder.
type PlaceOrderRequest struct {
	Body        Order
	HTTPRequest *http.Request
}

// GetOrderByIdRequest contains the request data for GetOrderById.
type GetOrderByIdRequest struct {
	OrderId     int64
	HTTPRequest *http.Request
}

// DeleteOrderRequest contains the request data for DeleteOrder.
type DeleteOrderRequest struct {
	OrderId     int64
	HTTPRequest *http.Request
}

// CreateUserRequest contains the request data for CreateUser.
type CreateUserRequest struct {
	Body        User
	HTTPRequest *http.Request
}

// CreateUsersWithArrayInputRequest contains the request data for CreateUsersWithArrayInput.
type CreateUsersWithArrayInputRequest struct {
	Body        []User
	HTTPRequest *http.Request
}

// CreateUsersWithListInputRequest contains the request data for CreateUsersWithListInput.
type CreateUsersWithListInputRequest struct {
	Body        []User
	HTTPRequest *http.Request
}

// LoginUserRequest contains the request data for LoginUser.
type LoginUserRequest struct {
	Username    string
	Password    string
	HTTPRequest *http.Request
}

// LogoutUserRequest contains the request data for LogoutUser.
type LogoutUserRequest struct {
	HTTPRequest *http.Request
}

// GetUserByNameRequest contains the request data for GetUserByName.
type GetUserByNameRequest struct {
	Username    string
	HTTPRequest *http.Request
}

// UpdateUserRequest contains the request data for UpdateUser.
type UpdateUserRequest struct {
	Username    string
	Body        User
	HTTPRequest *http.Request
}

// DeleteUserRequest contains the request data for DeleteUser.
type DeleteUserRequest struct {
	Username    string
	HTTPRequest *http.Request
}

// UnimplementedServer provides default implementations that return errors.
type UnimplementedServer struct{}

func (s *UnimplementedServer) UpdatePet(ctx context.Context, req *UpdatePetRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) AddPet(ctx context.Context, req *AddPetRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) FindPetsByStatus(ctx context.Context, req *FindPetsByStatusRequest) ([]Pet, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) FindPetsByTags(ctx context.Context, req *FindPetsByTagsRequest) ([]Pet, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) GetPetById(ctx context.Context, req *GetPetByIdRequest) (*Pet, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) UpdatePetWithForm(ctx context.Context, req *UpdatePetWithFormRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) DeletePet(ctx context.Context, req *DeletePetRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) UploadFile(ctx context.Context, req *UploadFileRequest) (*ApiResponse, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) GetInventory(ctx context.Context, req *GetInventoryRequest) (map[string]int32, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*Order, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) GetOrderById(ctx context.Context, req *GetOrderByIdRequest) (*Order, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) DeleteOrder(ctx context.Context, req *DeleteOrderRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) CreateUsersWithArrayInput(ctx context.Context, req *CreateUsersWithArrayInputRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) CreateUsersWithListInput(ctx context.Context, req *CreateUsersWithListInputRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) LoginUser(ctx context.Context, req *LoginUserRequest) (*string, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) LogoutUser(ctx context.Context, req *LogoutUserRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) GetUserByName(ctx context.Context, req *GetUserByNameRequest) (*User, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

func (s *UnimplementedServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*http.Response, error) {
	return nil, ErrNotImplemented
}

// ErrNotImplemented is returned by UnimplementedServer methods.
var ErrNotImplemented = &NotImplementedError{}

// NotImplementedError indicates an operation is not implemented.
type NotImplementedError struct{}

func (e *NotImplementedError) Error() string { return "not implemented" }
