// Code generated by oastools. DO NOT EDIT.

package petstore

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"strings"
	"sync"
)

// CredentialProvider provides credentials for authentication.
// Implementations can fetch credentials from various sources like environment
// variables, configuration files, secret managers, or in-memory storage.
type CredentialProvider interface {
	// GetCredential returns the credential value for the given name.
	// Returns an error if the credential cannot be found or retrieved.
	GetCredential(ctx context.Context, name string) (string, error)
}

// MemoryCredentialProvider stores credentials in memory.
// This is useful for testing or when credentials are loaded at startup.
type MemoryCredentialProvider struct {
	credentials map[string]string
	mu          sync.RWMutex
}

// NewMemoryCredentialProvider creates a new in-memory credential provider.
func NewMemoryCredentialProvider() *MemoryCredentialProvider {
	return &MemoryCredentialProvider{
		credentials: make(map[string]string),
	}
}

// Set stores a credential value.
func (p *MemoryCredentialProvider) Set(name, value string) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.credentials[name] = value
}

// Delete removes a credential.
func (p *MemoryCredentialProvider) Delete(name string) {
	p.mu.Lock()
	defer p.mu.Unlock()
	delete(p.credentials, name)
}

// GetCredential retrieves a credential from memory.
func (p *MemoryCredentialProvider) GetCredential(ctx context.Context, name string) (string, error) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	if val, ok := p.credentials[name]; ok {
		return val, nil
	}
	return "", fmt.Errorf("credential %q not found", name)
}

// EnvCredentialProvider reads credentials from environment variables.
// It supports an optional prefix to namespace credentials.
type EnvCredentialProvider struct {
	prefix string
}

// NewEnvCredentialProvider creates a provider that reads from environment variables.
// If prefix is "MYAPP_", credential "api_key" reads from "MYAPP_API_KEY".
// If prefix is empty, credential "api_key" reads from "API_KEY".
func NewEnvCredentialProvider(prefix string) *EnvCredentialProvider {
	return &EnvCredentialProvider{prefix: prefix}
}

// GetCredential retrieves a credential from environment variables.
// The credential name is converted to uppercase and hyphens are replaced with underscores.
func (p *EnvCredentialProvider) GetCredential(ctx context.Context, name string) (string, error) {
	envName := p.prefix + strings.ToUpper(strings.ReplaceAll(name, "-", "_"))
	if val := os.Getenv(envName); val != "" {
		return val, nil
	}
	return "", fmt.Errorf("environment variable %q not set", envName)
}

// CredentialChain tries multiple credential providers in order.
// This enables fallback behavior, e.g., try memory first, then environment.
type CredentialChain struct {
	providers []CredentialProvider
}

// NewCredentialChain creates a chain of credential providers.
// Providers are tried in the order they are passed.
func NewCredentialChain(providers ...CredentialProvider) *CredentialChain {
	return &CredentialChain{providers: providers}
}

// GetCredential tries each provider in order until one succeeds.
func (c *CredentialChain) GetCredential(ctx context.Context, name string) (string, error) {
	var lastErr error
	for _, p := range c.providers {
		val, err := p.GetCredential(ctx, name)
		if err == nil {
			return val, nil
		}
		lastErr = err
	}
	if lastErr != nil {
		return "", fmt.Errorf("no provider could supply credential %q: %w", name, lastErr)
	}
	return "", fmt.Errorf("no providers configured")
}

// WithCredentialProvider configures the client to use a credential provider.
// The credential is fetched before each request and set as a Bearer token.
func WithCredentialProvider(provider CredentialProvider, credentialName string) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, func(ctx context.Context, req *http.Request) error {
			cred, err := provider.GetCredential(ctx, credentialName)
			if err != nil {
				return fmt.Errorf("failed to get credential: %w", err)
			}
			req.Header.Set("Authorization", "Bearer "+cred)
			return nil
		})
		return nil
	}
}

// WithCredentialProviderHeader is like WithCredentialProvider but sets a custom header.
func WithCredentialProviderHeader(provider CredentialProvider, credentialName, headerName string) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, func(ctx context.Context, req *http.Request) error {
			cred, err := provider.GetCredential(ctx, credentialName)
			if err != nil {
				return fmt.Errorf("failed to get credential: %w", err)
			}
			req.Header.Set(headerName, cred)
			return nil
		})
		return nil
	}
}
