name: "Join with accept-right strategy"
description: "Tests that accept-right keeps the second document's schema on collision"

inputs:
  - base: petstore-oas30
    as: "service-a"
  - base: petstore-oas30
    as: "service-b"
    problems:
      duplicate-schema-different:
        - name: Pet

pipeline:
  - step: parse-all
  - step: join
    config:
      schema-strategy: accept-right
      path-strategy: accept-left
  - step: validate
    expect: valid
    assertions:
      - schemas-exist:
          - Pet
          - NewPet
