name: "Join with rename-left strategy"
description: "Tests that rename-left renames the left schema and keeps right unchanged"

inputs:
  - base: petstore-oas30
    as: "service-a"
  - base: petstore-oas30
    as: "service-b"
    problems:
      duplicate-schema-different:
        - name: Pet

pipeline:
  - step: parse-all
  - step: join
    config:
      schema-strategy: rename-left
      path-strategy: accept-left
  - step: validate
    expect: valid
    assertions:
      - schemas-exist:
          - Pet
          - NewPet
