swagger: "2.0"
info:
  title: Legacy Pet API
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /pets:
    get:
      operationId: listPets
      summary: List all pets
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
    post:
      operationId: createPet
      summary: Create a pet
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/NewPet'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Pet'
  /pets/{petId}:
    get:
      operationId: getPet
      summary: Get a pet
      parameters:
        - name: petId
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Pet'
definitions:
  Pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  NewPet:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string
  UnusedSchema:
    type: object
    description: This schema is not referenced anywhere
    properties:
      unused:
        type: string
