openapi: "3.0.3"
info:
  title: Orders API
  version: "1.0.0"
  description: Order management microservice
servers:
  - url: https://orders.example.com/v1
    description: Orders service
tags:
  - name: orders
    description: Order operations
paths:
  /orders:
    get:
      operationId: listOrders
      summary: List all orders
      tags: [orders]
      parameters:
        - name: userId
          in: query
          schema:
            type: integer
          description: Filter by user ID
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        "200":
          description: Order list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: createOrder
      summary: Create an order
      tags: [orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
      responses:
        "201":
          description: Order created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /orders/{orderId}:
    get:
      operationId: getOrder
      summary: Get order by ID
      tags: [orders]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Order:
      type: object
      required: [id, userId, total]
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        total:
          type: number
          format: double
        status:
          type: string
          enum: [pending, confirmed, shipped, delivered]
    CreateOrderRequest:
      type: object
      required: [userId, items]
      properties:
        userId:
          type: integer
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: integer
              quantity:
                type: integer
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
