name: "Convert OAS 2.0 to OAS 3.0"
description: "Tests conversion from Swagger 2.0 to OpenAPI 3.0"

base: petstore-oas2

pipeline:
  - step: parse
  - step: convert
    config:
      target-version: "3.0.3"
    assertions:
      - target-version: "3.0.3"
  - step: validate
    expect: valid
    assertions:
      - schemas-exist:
          - Pet
          - NewPet
