name: "Convert OAS 3.0 to OAS 2.0"
description: "Tests conversion from OpenAPI 3.0 to Swagger 2.0"

base: petstore-oas30

pipeline:
  - step: parse
  - step: convert
    config:
      target-version: "2.0"
    assertions:
      - target-version: "2.0"
  - step: validate
    expect: valid
    assertions:
      - schemas-exist:
          - Pet
          - NewPet
