openapi: "3.0.3"
info:
  title: CRM API
  version: "1.0.0"
paths:
  /accounts:
    get:
      operationId: listCRMAccounts
      tags: [crm]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
  /accounts/{accountId}/contacts:
    get:
      operationId: getContacts
      tags: [crm]
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Contact"
components:
  schemas:
    Account:
      type: object
      required: [accountId, companyName]
      properties:
        accountId:
          type: string
          format: uuid
        companyName:
          type: string
        industry:
          type: string
        employeeCount:
          type: integer
        annualRevenue:
          type: number
          format: double
    Contact:
      type: object
      properties:
        contactId:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
