name: "Join then generate"
description: "Joins two specs then generates a unified client"

inputs:
  - base: petstore-oas30
    as: "pets-service"
  - base: petstore-oas31
    as: "events-service"

pipeline:
  - step: parse-all
  - step: join
    config:
      schema-strategy: accept-left
      path-strategy: accept-left
  - step: validate
    expect: valid
  - step: generate
    config:
      client: true
      package: "unified"
  - step: build
    expect: success
